const KEY='eightfaces-lifeos-v1',SECRET='eightfaces-lifeos-secret',BLOB='https://jsonblob.com/api/jsonBlob';
const D=[
{id:'family',name:'家庭',color:'#e07a5f',hint:'父母、伴侶、子女'},
{id:'friends',name:'友情',color:'#7eb89a',hint:'朋友、舊識'},
{id:'career',name:'事業',color:'#6b90c4',hint:'工作、技能'},
{id:'wealth',name:'財富',color:'#e2b657',hint:'收支、儲蓄'},
{id:'hobby',name:'興趣',color:'#e8b88a',hint:'純粹玩'},
{id:'body',name:'身心',color:'#6cb4b0',hint:'瞑、食、郁'},
{id:'growth',name:'成長',color:'#a494d6',hint:'學習'},
{id:'inner',name:'內心',color:'#d489b0',hint:'信念、價值'}
];
const ACT={family:['傳訊問家人今日食咗哪','專心陪 20 分鐘'],friends:['搜一個好耐無聯絡嘅朋友','約人飲茶'],career:['寫低唯一最重要那件工作','問自己係咪用工作逃避'],wealth:['睇一眼今個月花咗哪','應急錢夠撐幾耐'],hobby:['今日俾 20 分鐘玩','做一件無人評分嘅事'],body:['今晚提早半小時瞑','行 15 分鐘'],growth:['讀 10 頁或學 15 分鐘','用三句總結最近學到嘅'],inner:['寫五句：我而家真正在意哪','坐兩分鐘唔刷電話']};
const PQ=['我而家真正驚哪？','我用忙碌遮咗邊樣嘢？','如果一年後後悔，會後悔忽略邊個面向？'];
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>Math.random().toString(36).slice(2,9);
const days=iso=>iso?Math.floor((Date.now()-new Date(iso))/864e5):999;
function blank(){return{focus:'',tasks:[],habits:[],notes:[],lastActivity:null}}
function def(){const domains={},scores={};D.forEach(d=>{domains[d.id]=blank();scores[d.id]={satisfaction:5,updatedAt:null}});return{profile:{name:''},energy:{date:today(),level:'mid'},scores,domains,people:[],inner:{manifesto:'',values:'',principles:'',prompts:[]},weekly:{focuses:[],lastReview:null,history:[],season:{mode:'balance',note:''}},checkins:[],actionIndex:{},meta:{updatedAt:Date.now()},cloud:{blobId:'',auto:true,lastSync:null,lastError:''}}}
function load(){try{const p=JSON.parse(localStorage.getItem(KEY)||'null');if(!p)return def();const b=def();return Object.assign(b,p,{scores:Object.assign(b.scores,p.scores||{}),domains:Object.assign(b.domains,p.domains||{}),inner:Object.assign(b.inner,p.inner||{}),weekly:Object.assign(b.weekly,p.weekly||{}),cloud:Object.assign(b.cloud,p.cloud||{})})}catch(e){return def()}}
let state=load(),cur='family',pick=0,syncing=false,timer=null;
const getPass=()=>{try{return JSON.parse(localStorage.getItem(SECRET)||'{}').pass||''}catch(e){return ''}};
const setPass=p=>localStorage.setItem(SECRET,JSON.stringify({pass:p}));
function save(o){state.meta={updatedAt:Date.now()};localStorage.setItem(KEY,JSON.stringify(state));if(!o||o.sync!==false){if(state.cloud.auto&&state.cloud.blobId&&getPass()){clearTimeout(timer);timer=setTimeout(()=>push(true),1200)}}pill()}
function pill(m,t){const el=document.getElementById('sync-pill');if(!el)return;el.className='sync-pill'+(m?' '+m:state.cloud.lastError?' err':state.cloud.blobId&&state.cloud.lastSync?' ok':'');el.querySelector('span').textContent=t||(syncing?'同步中':state.cloud.lastError?'同步失敗':state.cloud.blobId&&state.cloud.lastSync?'雲端已連':'本機')}
function go(p){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));const el=document.getElementById('page-'+p);if(el)el.classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===p||(p==='domain'&&b.dataset.go==='domains')||(p==='checkin'&&b.dataset.go==='home')));if(p==='home')home();if(p==='domains')cards();if(p==='domain')dom();if(p==='people')people();if(p==='inner')inner();if(p==='review')review();if(p==='checkin')check();if(p==='settings')settings();window.scrollTo(0,0)}
function by(id){return D.find(d=>d.id===id)}
function neglected(){return D.map(d=>({id:d.id,w:days(state.domains[d.id].lastActivity)*1.4+(10-(state.scores[d.id].satisfaction||5))})).sort((a,b)=>b.w-a.w)[0]}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&','<':'<','>':'>','"':'"',"'":'&#39;'}[c]))}
function touch(id){state.domains[id].lastActivity=today();state.scores[id].updatedAt=today()}
function home(){const n=state.profile.name;document.getElementById('hello').textContent=(n?n+'，':'')+'人生唔止一個面向。今日睇清楚自己偏咗邊。';draw();document.getElementById('score-list').innerHTML=D.map(d=>`<div class="score-item" data-open="${d.id}"><i class="dot" style="background:${d.color}"></i><b>${d.name}</b><span>${state.scores[d.id].satisfaction}/10</span></div>`).join('');document.querySelectorAll('#energy .chip').forEach(c=>c.classList.toggle('active',c.dataset.energy===state.energy.level));const ng=neglected(),list=ACT[ng.id],i=(state.actionIndex[ng.id]||0)%list.length;pick=i;const idle=days(state.domains[ng.id].lastActivity);document.getElementById('today-action').innerHTML=`<strong>${by(ng.id).name} · ${idle>=900?'從未紀錄':' 已 '+idle+' 日冊更新'}</strong>${list[i]}`;const al=[];D.forEach(d=>{const x=days(state.domains[d.id].lastActivity);if(x>=14)al.push(`<div class="alert">${d.name} 已 ${x>=900?'從未':x+' 日未'}更新。</div>`)});if(!state.weekly.lastReview||days(state.weekly.lastReview)>=8)al.push('<div class="alert">該做週檢了。</div>');document.getElementById('alerts').innerHTML=al.join('')||'<div class="alert ok">呢週未見明顯空白。</div>';document.getElementById('focus-list').innerHTML=(state.weekly.focuses||[]).map(f=>`<div class="item"><div class="grow">${esc(f)}</div></div>`).join('')||'<div class="empty">未定本週三件事。</div>'}
function draw(){const c=document.getElementById('wheel'),x=c.getContext('2d'),w=c.width,h=c.height;x.clearRect(0,0,w,h);const cx=w/2,cy=h/2+6,r=Math.min(w,h)*0.36,n=D.length;x.strokeStyle='rgba(243,232,214,0.12)';for(let k=2;k<=10;k+=2){x.beginPath();for(let i=0;i<=n;i++){const a=-Math.PI/2+Math.PI*2*i/n,X=cx+Math.cos(a)*r*k/10,Y=cy+Math.sin(a)*r*k/10;i?x.lineTo(X,Y):x.moveTo(X,Y)}x.closePath();x.stroke()}x.beginPath();D.forEach((d,i)=>{const v=(state.scores[d.id].satisfaction||1)/10,a=-Math.PI/2+Math.PI*2*i/n,X=cx+Math.cos(a)*r*v,Y=cy+Math.sin(a)*r*v;i?x.lineTo(X,Y):x.moveTo(X,Y)});x.closePath();x.fillStyle='rgba(196,165,116,0.22)';x.strokeStyle='#c4a574';x.lineWidth=2;x.fill();x.stroke();x.font="13px 'Noto Sans TC',sans-serif";x.textAlign='center';x.textBaseline='middle';D.forEach((d,i)=>{const a=-Math.PI/2+Math.PI*2*i/n;x.fillStyle=d.color;x.fillText(d.name,cx+Math.cos(a)*(r+28),cy+Math.sin(a)*(r+28))})}
function cards(){document.getElementById('domain-cards').innerHTML=D.map(d=>`<div class="card domain-card" data-open="${d.id}"><div class="kicker">${d.hint}</div><h3 style="color:${d.color}">${d.name}</h3><div class="meter"><i style="width:${state.scores[d.id].satisfaction*10}%;background:${d.color}"></i></div><div class="row"><span>${state.scores[d.id].satisfaction}/10</span></div></div>`).join('')}
function dom(){const d=by(cur),r=state.domains[cur],s=state.scores[cur];document.getElementById('d-title').innerHTML=`<span style="color:${d.color}">${d.name}</span>`;document.getElementById('d-score').value=s.satisfaction;document.getElementById('d-score-val').textContent=s.satisfaction;document.getElementById('d-focus').value=r.focus||'';document.getElementById('d-tasks').innerHTML=r.tasks.map(t=>`<div class="item"><input type="checkbox" ${t.done?'checked':''} data-toggle-task="${t.id}"><div class="grow">${esc(t.text)}</div><button class="icon-btn" data-del-task="${t.id}">刪</button></div>`).join('')||'<div class="empty">最多三件。</div>';document.getElementById('d-habits').innerHTML=r.habits.map(h=>`<div class="item"><input type="checkbox" ${(h.log&&h.log[today()])?'checked':''} data-toggle-habit="${h.id}"><div class="grow">${esc(h.name)}</div><button class="icon-btn" data-del-habit="${h.id}">刪</button></div>`).join('')||'<div class="empty">一至兩個習慣。</div>';document.getElementById('d-notes').innerHTML=r.notes.slice(0,12).map(n=>`<div><b>${n.date}</b><div>${esc(n.text)}</div></div>`).join('')||'未有日誌。'}
function people(){document.getElementById('people-list').innerHTML=state.people.length?state.people.map(p=>`<div class="item"><div class="grow"><b>${esc(p.name)}</b> <span class="pill">${esc(p.relation||'')}</span><div class="muted">上次：${p.lastContact||'未記'} · ${p.lastContact?days(p.lastContact)+' 日':''}</div></div><button class="btn" data-edit-person="${p.id}">更新</button></div>`).join(''):'<div class="empty">未加人。</div>'}
function inner(){document.getElementById('manifesto').value=state.inner.manifesto||'';document.getElementById('values').value=state.inner.values||'';document.getElementById('principles').value=state.inner.principles||'';document.getElementById('prompt-box').innerHTML='<strong>今日一問</strong>'+PQ[new Date().getDate()%PQ.length];document.getElementById('prompt-hist').innerHTML=(state.inner.prompts||[]).slice(0,8).map(p=>`<div><b>${p.date}</b> · ${esc(p.q)}<div>${esc(p.a)}</div></div>`).join('')||''}
function review(){document.getElementById('review-sliders').innerHTML=D.map(d=>`<label class="field">${d.name}</label><div class="range-wrap"><input type="range" min="1" max="10" value="${state.scores[d.id].satisfaction}" data-rev="${d.id}"><b>${state.scores[d.id].satisfaction}</b></div>`).join('');document.getElementById('review-focus').value=(state.weekly.focuses||[]).join('\n')}
function check(){document.getElementById('checkin-hot').innerHTML=D.map(d=>`<option value="${d.id}">${d.name}</option>`).join('')}
function settings(){const a=document.getElementById('profile-name');if(!a)return;a.value=state.profile.name||'';document.getElementById('cloud-id').value=state.cloud.blobId||'';document.getElementById('cloud-pass').value=getPass();document.getElementById('cloud-auto').checked=state.cloud.auto!==false;document.getElementById('cloud-status').textContent=state.cloud.lastError||state.cloud.lastSync||'未開通雲端。';pill()}
async function enc(){const pass=getPass();if(!pass)throw new Error('未設密碼');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12));const base=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:12e4,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);const data=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(state)));const b64=buf=>btoa(String.fromCharCode(...new Uint8Array(buf)));return{v:1,app:'eightfaces',updatedAt:state.meta.updatedAt,salt:b64(salt),iv:b64(iv),data:b64(data)}}
async function dec(pack){const pass=getPass();const u=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));const base=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:u(pack.salt),iterations:12e4,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:u(pack.iv)},key,u(pack.data));return JSON.parse(new TextDecoder().decode(plain))}
async function createCloud(){const pass=(document.getElementById('cloud-pass').value||getPass()).trim();if(pass.length<8)return alert('密碼至少 8 個字');setPass(pass);try{const pack=await enc();const res=await fetch(BLOB,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(pack)});if(!res.ok)throw new Error('開通失敗 '+res.status);const id=res.headers.get('x-jsonblob')||(res.headers.get('Location')||'').split('/').pop();state.cloud.blobId=id;state.cloud.lastSync=new Date().toISOString();state.cloud.lastError='';save({sync:false});alert('已開通，請抄低編號同密碼。')}catch(e){alert(String(e.message||e))}settings()}
async function push(silent){if(!state.cloud.blobId||!getPass())return;try{await fetch(BLOB+'/'+state.cloud.blobId,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(await enc())});state.cloud.lastSync=new Date().toISOString();state.cloud.lastError='';localStorage.setItem(KEY,JSON.stringify(state));pill('ok','已上傳')}catch(e){if(!silent)alert('上傳失敗')}}
async function pull(){try{const pack=await(await fetch(BLOB+'/'+state.cloud.blobId)).json();const remote=await dec(pack);const b=def();state=Object.assign(b,remote,{cloud:Object.assign(b.cloud,remote.cloud||{},{blobId:state.cloud.blobId})});state.cloud.lastSync=new Date().toISOString();save({sync:false});home();alert('已拉回')}catch(e){alert('拉回失敗，檢查編號或密碼')}}
const Rec=window.SpeechRecognition||window.webkitSpeechRecognition;const draft={step:0,energy:'mid',hot:'career',note:''};
function parseE(t){t=t.replace(/\s/g,'');if(/低|攔|累|無力/.test(t))return'low';if(/高|精神|好醒/.test(t))return'high';if(/中|普通|一般/.test(t))return'mid';return null}
function parseD(t){t=t.replace(/\s/g,'');if(/家庭|屋企|父母/.test(t))return'family';if(/友情|朋友/.test(t))return'friends';if(/事業|工作|加班/.test(t))return'career';if(/財富|錢/.test(t))return'wealth';if(/興趣|玩/.test(t))return'hobby';if(/身心|健康|瞑/.test(t))return'body';if(/成長|學習/.test(t))return'growth';if(/內心|信念/.test(t))return'inner';return null}
function openV(){draft.step=0;draft.energy=state.energy.level;draft.hot='career';draft.note='';document.getElementById('voice-modal').classList.add('show');document.getElementById('voice-q').textContent='能量高中低？之後講今日最多時間嘅面向。'}
function listen(){if(!Rec){document.getElementById('voice-live').textContent='用 Chrome / Safari';return}const r=new Rec();r.lang='zh-HK';r.onresult=ev=>{const t=ev.results[0][0].transcript;document.getElementById('voice-live').textContent=t;const e=parseE(t),d=parseD(t);if(e)draft.energy=e;if(d)draft.hot=d;if(!e&&!d)draft.note=t};r.start()}
document.body.addEventListener('click',e=>{const g=e.target.closest('[data-go]');if(g){go(g.dataset.go);return}const o=e.target.closest('[data-open]');if(o){cur=o.dataset.open;go('domain');return}const en=e.target.closest('[data-energy]');if(en){state.energy={date:today(),level:en.dataset.energy};save();document.querySelectorAll('#energy .chip,#checkin-energy .chip').forEach(c=>c.classList.toggle('active',c.dataset.energy===state.energy.level))}const se=e.target.closest('[data-season]');if(se){state.weekly.season=state.weekly.season||{mode:'balance',note:''};state.weekly.season.mode=se.dataset.season;save()}});
const $=id=>document.getElementById(id);
$('do-action').onclick=()=>{const n=neglected();touch(n.id);state.domains[n.id].notes.unshift({id:uid(),date:today(),text:'完成：'+ACT[n.id][pick]});save();home()};
$('shuffle-action').onclick=()=>{const n=neglected();state.actionIndex[n.id]=(state.actionIndex[n.id]||0)+1;save();home()};
$('d-score').oninput=e=>{state.scores[cur].satisfaction=+e.target.value;$('d-score-val').textContent=e.target.value;save()};
$('d-focus').onchange=e=>{state.domains[cur].focus=e.target.value;touch(cur);save()};
$('d-add-task').onclick=()=>{const t=$('d-task-input').value.trim();if(!t)return;if(state.domains[cur].tasks.filter(x=>!x.done).length>=3)return alert('最多三件');state.domains[cur].tasks.unshift({id:uid(),text:t,done:false});$('d-task-input').value='';touch(cur);save();dom()};
$('d-add-habit').onclick=()=>{const t=$('d-habit-input').value.trim();if(!t)return;if(state.domains[cur].habits.length>=2)return alert('最多兩個');state.domains[cur].habits.push({id:uid(),name:t,log:{}});$('d-habit-input').value='';touch(cur);save();dom()};
$('page-domain').addEventListener('click',e=>{const t=e.target;if(t.dataset.toggleTask){const x=state.domains[cur].tasks.find(z=>z.id===t.dataset.toggleTask);if(x)x.done=t.checked;touch(cur);save();dom()}if(t.dataset.delTask){state.domains[cur].tasks=state.domains[cur].tasks.filter(z=>z.id!==t.dataset.delTask);save();dom()}if(t.dataset.toggleHabit){const h=state.domains[cur].habits.find(z=>z.id===t.dataset.toggleHabit);h.log=h.log||{};if(t.checked)h.log[today()]=true;else delete h.log[today()];touch(cur);save();dom()}if(t.dataset.delHabit){state.domains[cur].habits=state.domains[cur].habits.filter(z=>z.id!==t.dataset.delHabit);save();dom()}});
$('d-save-note').onclick=()=>{const t=$('d-note').value.trim();if(!t)return;state.domains[cur].notes.unshift({id:uid(),date:today(),text:t});$('d-note').value='';touch(cur);save();dom()};
$('add-person').onclick=()=>{const name=prompt('名字');if(!name)return;state.people.push({id:uid(),name,relation:'朋友',lastContact:today(),cadence:14,note:''});touch('friends');save();people()};
$('save-inner').onclick=()=>{state.inner.manifesto=$('manifesto').value;state.inner.values=$('values').value;state.inner.principles=$('principles').value;touch('inner');save()};
$('save-prompt').onclick=()=>{const a=$('prompt-ans').value.trim();if(!a)return;state.inner.prompts.unshift({date:today(),q:$('prompt-box').innerText,a});$('prompt-ans').value='';touch('inner');save();inner()};
$('review-sliders').addEventListener('input',e=>{if(e.target.dataset.rev)e.target.nextElementSibling.textContent=e.target.value});
$('save-review').onclick=()=>{document.querySelectorAll('[data-rev]').forEach(sl=>{state.scores[sl.dataset.rev].satisfaction=+sl.value;state.scores[sl.dataset.rev].updatedAt=today()});state.weekly.focuses=$('review-focus').value.split('\n').map(s=>s.trim()).filter(Boolean).slice(0,3);state.weekly.lastReview=today();state.weekly.season.note=$('season-note').value;save();go('home')};
$('save-checkin').onclick=()=>{const hot=$('checkin-hot').value;state.checkins.unshift({date:today(),energy:state.energy.level,hot,note:$('checkin-note').value});touch(hot);save();go('home')};
$('save-name').onclick=()=>{state.profile.name=$('profile-name').value.trim();save()};
$('export-data').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='eightfaces-'+today()+'.json';a.click()};
$('import-data').onclick=()=>$('import-file').click();
$('import-file').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{state=Object.assign(def(),JSON.parse(r.result));save();go('home')};r.readAsText(f)};
$('reset-data').onclick=()=>{if(confirm('清空？')){state=def();save({sync:false});go('home')}};
$('cloud-create').onclick=createCloud;
$('cloud-push').onclick=()=>{state.cloud.blobId=$('cloud-id').value.trim();const p=$('cloud-pass').value.trim();if(p)setPass(p);push(false)};
$('cloud-pull').onclick=()=>{state.cloud.blobId=$('cloud-id').value.trim();const p=$('cloud-pass').value.trim();if(p)setPass(p);pull()};
$('cloud-copy').onclick=()=>navigator.clipboard.writeText($('cloud-id').value);
$('btn-voice').onclick=openV;$('btn-voice-2').onclick=openV;$('mic-btn').onclick=listen;
$('voice-save').onclick=()=>{state.energy={date:today(),level:draft.energy};state.checkins.unshift({date:today(),energy:draft.energy,hot:draft.hot,note:draft.note,via:'voice'});touch(draft.hot);save();$('voice-modal').classList.remove('show');go('home')};
$('voice-close').onclick=()=>$('voice-modal').classList.remove('show');
$('voice-skip').onclick=()=>$('voice-modal').classList.remove('show');
home();pill();
